In [102]:
import numpy
# Importa las funciones matematicas
class Formula:# Se crea una clase madre
    def __init__(self, lado):
        self.lado = lado
# Se crea una clase heredada
class Triangulo(Formula):
    def __init__(self, lado):
        ().__init__(lado)

    def area(self):
        # Área de un triángulo equilátero: (lado^2 * sqrt(3)) / 4
        return (self.lado ** 2 * numpy.sqrt(3)) / 4

    def perimetro(self):
        # Perímetro de un triángulo equilátero: lado * 3
        return self.lado * 3

In [100]:
class Mensaje(Formula):
  def __init__(self):
      print('Fin del programa')
  def fin(self):
      print('Gracias')

In [101]:
lado = 6
print("El área del Triángulo es:",triangulo.area())
print("El perimetro del Triángulo es:",triangulo.per())
mensaje = Mensaje()
mensaje.fin()

El área del Triángulo es: 15.588457268119894
El perimetro del Triángulo es: 18
Fin del programa
Gracias


In [75]:
import numpy as np
#Hacer una lista con 16 números random de un intervalo de 1-100
L = [i for i in np.random.randint (1,101, size=16)]
L


[39, 9, 33, 35, 11, 24, 16, 88, 26, 72, 93, 75, 63, 47, 33, 89]

In [76]:
# Definir una lista mediante el arreglo creado
L_arreglo =np.array(L)
L_arreglo

array([39,  9, 33, 35, 11, 24, 16, 88, 26, 72, 93, 75, 63, 47, 33, 89])

In [81]:
# Definir a la matriz como la lista creada y hacer que de una lista la convierta en una matriz
L_matriz= L_arreglo.reshape(4,4)
M_matriz = np.array([L_arreglo]).reshape(4,4)
M_matriz

array([[39,  9, 33, 35],
       [11, 24, 16, 88],
       [26, 72, 93, 75],
       [63, 47, 33, 89]])

In [95]:
# Sacar el determinante de la matriz
det= np.linalg.det(M_matriz)
tranpuesta = M_matriz.T

In [96]:
det

-8420689.999999987

In [98]:
tranpuesta

array([[39, 11, 26, 63],
       [ 9, 24, 72, 47],
       [33, 16, 93, 33],
       [35, 88, 75, 89]])